### ISSUE TITLE
Missing Proguard library config

### ISSUE THREAD

**Issue by cosminstefanxp** [shopgun/shopgun-android-sdk#14]
When using the library in a project that has minification enabled, the app will crash at startup due to missing resources. After digging through this, I've noticed the issue comes from EventBus. As such, some Proguard config must be shipped by the library:

```
-keepattributes *Annotation*
-keepclassmembers class * {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }
```
See: http://greenrobot.org/eventbus/documentation/proguard

**Comment by AgneseBussone** [comment]
Fix available in 4.0.3-rc2
