### ISSUE TITLE
Java 8 incompatibility.

### ISSUE THREAD

**Issue by jmintb** [shopgun/shopgun-android-sdk#6]
When attempting to compile:
'com.shopgun.android:sdk:4.0.1-beta'

I get an error relating to java 8 as seen below.
Is this because the shopgun sdk is compiled with Java 8?
Any ideas as to how to get around this?

Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.

**Comment by AgneseBussone** [comment]
Hi, were you able to solve the problem?
The sdk is compiled with java 7.

**Comment by jmintb** [comment]
I migrated the project to java 8, which solved the issue. I could not get it to compile using java 7.
