### ISSUE TITLE
Invalid link to old engineering blog

### ISSUE THREAD

**Issue by tbug** [shopgun/shopgun-android-sdk#7]
https://github.com/shopgun/shopgun-android-sdk/blob/3bbc6f825292f34e9a1cf2847cdb3846ffd01388/shopGunSdk/src/main/java/com/shopgun/android/sdk/model/User.java#L38

**Comment by AgneseBussone** [comment]
Commit ae0a87a1d67cb02e79d05fb8833779b707497145
